#ifndef UNIXSIGNALHANDERPLUGIN_GLOBAL_H
#define UNIXSIGNALHANDERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIXSIGNALHANDERPLUGIN_LIBRARY)
#  define UNIXSIGNALHANDERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNIXSIGNALHANDERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNIXSIGNALHANDERPLUGIN_GLOBAL_H
